server:
  port: 1234

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=honest_mark
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

crpt:
  api:
    timeunit: MINUTES
    request-limit: 3
    file-format: json
